version: "3.7"
services:
  web-server:
    build:
      dockerfile: dockerfile
      context: .
    container_name: trucorp-web-2.0
    restart: always
    volumes:
      - "./html/:/var/www/html/"
    depends_on:
      - mysql-server
    ports:
      - "7000:80"
  mysql-server:
    build:
      dockerfile: dockerfile1
      context: .
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "5000:80"
volumes:
  mysql-data:
